### ISSUE TITLE
How do I run the web component on a  non standard port?

### ISSUE THREAD

**Issue by gerroon** [simon987/sist2#23]
Hi

I would like to try the Docker route but your sample web server does not havea port and I have other services running on the system alread. Can you please tell me how I can run the web component on a custom exposed service port ?

Maybe you can tell us how to run the web server without network host mode and use exposed ports insetad?

thanks

**Comment by simon987** [comment]
Hi, first of all, sorry for the lack of documentation, I'll make my best to write a better guide soon

> Can you please tell me how I can run the web component on a custom exposed service port ?

If you are using Docker, you need to make sure that sist2 can see the elasticsearch instance. Assuming that you are running the elasticsearch docker image, you need put the two containers on the same network:

```bash
docker run -d --name my_elasticsearch --network sist2_net \
    -e "discovery.type=single-node" \
    docker.elastic.co/elasticsearch/elasticsearch:7.4.2
``` 

Then you can start sist2 like this:
```bash
docker run --rm --network sist2_net -d --name -p <PORT>:4090 sist2\
    -v $PWD/out/my_idx:/idx \
    -v $PWD/my/files:/files
    simon987/sist2 web /idx --bind 0.0.0.0 --es-url http://my_elasticsearch:9200
``` 

If you are using docker-compose, you can write something similar to this: 
```yaml
  sist2:
    image: simon987/sist2
    ports: 
      - <PORT>:4090
    command: web --bind 0.0.0.0 --es-url http://es:9200 /data/my_index 
    volumes:
      - ./indexes/:/data/
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1G -Xmx4G"
```

Finally if you are running the binary:
```
sist2 web --bind 0.0.0.0 --port <PORT> my_index/
```
