### ISSUE TITLE
Allow for in-place incremental scan

### ISSUE THREAD

**Issue by Poquaruse** [simon987/sist2#326]
**Which SIST2 component is your Feature Request related to?**
Incremental Scan

**Is your feature request related to a problem? Please describe.**
Currently, an incremental scan requires another output file, e.g. input and output index need to be different. It would be of great help if there was either the possibility to update in place or an automation to update and then replace the old index.

**What would you like to see happen?**
Run sist2 in a docker container and have automated regular incremental index updates (e.g. every night) without having to rebuild the whole index.

**Additional context**
A simple script (incremental scan, delete old index, rename new index) does not seem to work because web seems to use the new name automatically.

Thanks for this great project!

**Comment by simon987** [comment]
Hi, currently the recommended way to automate index updates is to use the "sist2-admin" web app bundled in the 2.13.X+ docker image. The app lets you specify a cron schedule etc. 

It's not officially released yet because I need to work on the documentation but you can start using it with this example compose file:

![image](https://user-images.githubusercontent.com/7120851/213897722-33939ed8-9b4a-4fd6-b250-8a55589c990a.png)


```yml
version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.14.0
    restart: always
    container_name: sist2-es
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  sist2-admin:
    image: simon987/sist2:x64-linux
    restart: always
    container_name: sist2-admin
    volumes:
      - ${PATH_TO_CONFIG_FOLDER}:/sist2-admin/
      - ${PATH_TO_FILES_TO_BE_SCANNED}:/data
    ports:
      - 127.0.0.1:8080:8080
      - 4090:4090
    working_dir: /root/sist2-admin/
    entrypoint: python3
    command:
      - /root/sist2-admin/sist2_admin/app.py
```
