### ISSUE TITLE
Scan: Child process crashed (Segmentation fault)

### ISSUE THREAD

**Issue by EvgeniyDoctor** [simon987/sist2#377]
**Device Information (please complete the following information):**
 - OS: DSM 6
 - Deployment: Docker
 - Browser *(if relevant)*: `[e.g., chrome, safari]`
 - SIST2 Version: `[e.g., v2.9.0]`
 - Elasticsearch Version *(if relevant)* : ``

**Command with arguments** 
```
version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elastic
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "ingest.geoip.downloader.enabled=false"
    deploy:
      resources:
        limits:
          memory: 2g

  sist2-admin:
    image: simon987/sist2:3.1.0-x64-linux
    container_name: sist2
    restart: unless-stopped
    volumes:
      - /sist2/data:/sist2-admin
      - "/books:/host/books"
      - "/host/books/notes" # exclude
      - "/books/notes:/host/notes"
    ports:
      - 4090:4090 # sist2
      - 4091:8080 # sist2-admin
    working_dir: /root/sist2-admin/
    entrypoint: python3 /root/sist2-admin/sist2_admin/app.py
    deploy:
      resources:
        limits:
          memory: 512m
```

**Describe the bug**

I have a lot of books in PDF format. 0 of them indexed, crashed with this error:
```
2023-06-28 06:14:49 [DEBUG database.c] Opening database /dev/shm/sist2-ipc-13.sqlite (2)
2023-06-28 06:14:49 [DEBUG /host/books/Ницше/По ту сторону добра и зла.pdf] Starting parse job {67d8e5ff6420e8b72ac288be6543a4da}
2023-06-28 06:14:49 [DEBUG tpool.c] Waiting for worker threads to finish
2023-06-28 06:14:59 [DEBUG tpool.c] Child process terminated with status code 0
2023-06-28 06:14:59 [FATAL tpool.c] Child process crashed (Segmentation fault).
                                         The process was working on /host/books/Ницше/По ту сторону добра и зла.pdf
                                         Please consider creating a bug report at https://github.com/simon987/sist2/issues !
                                         sist2 is an open source project and relies on the collaboration of its users to diagnose and fix bugs.
```

If i enable OCR, i see this error:
```
2023-06-28 06:59:18 [FATAL cli.c] Invalid PATH argument. File not found: /sist2-admin/scan-Books-2023-06-28 06:59:17.380264.sist2
 [ADMIN ] Sist2Scan task finished return_code=-10, duration=datetime.timedelta(microseconds=6770)
```

Also pay your attention to this line in my docker-compose, because i think it caused the last error:
`- "/host/books/notes" # exclude`

**Steps To Reproduce**
Please be specific!
3. etc.

**Expected behavior**

**Actual Behavior**

**Screenshots**

**Additional context**

I have books in russian and english.

**Comment by simon987** [comment]
Hi, could you attach this `/books/Ницше/По ту сторону добра и зла.pdf` file here or send it privately to me by email at me@simon987.net so I can test it?

**Comment by EvgeniyDoctor** [comment]
I just tried to delete the `data` folder, delete both containers and remove exclude line from docker-compose:
```
version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elastic
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "ingest.geoip.downloader.enabled=false"
    deploy:
      resources:
        limits:
          memory: 2g

  sist2-admin:
    image: simon987/sist2:3.1.0-x64-linux
    container_name: sist2
    restart: unless-stopped
    volumes:
      - /sist2/data:/sist2-admin
      - "/books:/host/books" # <--- here
    ports:
      - 4090:4090 # sist2
      - 4091:8080 # sist2-admin
    working_dir: /root/sist2-admin/
    entrypoint: python3 /root/sist2-admin/sist2_admin/app.py
    deploy:
      resources:
        limits:
          memory: 512m
```
It does not help. I also tried to delete memory limits - no luck.

Inside the `sist2` container files and dirs of `/host/books` has at least 755 rights and normal owner.
And i sent you the book.
