### ISSUE TITLE
Wrong encoding for viewing files

### ISSUE THREAD

**Issue by EvgeniyDoctor** [simon987/sist2#378]
**Device Information (please complete the following information):**
 - OS: DSM 6
 - Deployment: Docker
 - Browser *(if relevant)*: `[e.g., chrome, safari]`
 - SIST2 Version: `[e.g., v2.9.0]`
 - Elasticsearch Version *(if relevant)* : ``

**Command with arguments** 

```
version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    container_name: elastic
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "ingest.geoip.downloader.enabled=false"
    deploy:
      resources:
        limits:
          memory: 2g

  sist2-admin:
    image: simon987/sist2:3.1.0-x64-linux
    container_name: sist2
    restart: unless-stopped
    volumes:
      - /sist2/data:/sist2-admin
      - "/books:/host/books"
      - "/host/books/notes" # exclude
      - "/books/notes:/host/notes"
    ports:
      - 4090:4090 # sist2
      - 4091:8080 # sist2-admin
    working_dir: /root/sist2-admin/
    entrypoint: python3 /root/sist2-admin/sist2_admin/app.py
    deploy:
      resources:
        limits:
          memory: 512m
```

**Describe the bug**

I have txt files with cyrillic chars in utf8, but when i open it by link in sist2, i see broken encoding.
Link like: `http://ip:port/f/hash1/hash2`

**Steps To Reproduce**
Please be specific!
1. create a txt file with cyrillic chars in utf8 in it
2. index it
3. open in web UI

**Expected behavior**

I should see normal cyrillic letters.

**Actual Behavior**

I see this:
```
2021

		Ð“Ð›ÐÐ’Ð 1

	Ð­Ð¼Ð¾Ñ†Ð¸Ð¸ Ð² Ñ€Ð°Ð·Ð½Ñ‹Ñ… ÐºÑƒÐ»ÑŒÑ‚ÑƒÑ€Ð°Ñ…

Ð­Ð¼Ð¾Ñ†Ð¸Ñ - ÑÑ‚Ð¾ Ð¿Ñ€Ð¾Ñ†ÐµÑÑ, ...
```
**Screenshots**

**Additional context**

On the main page of the web UI cyrillic letters are not broken.
