### ISSUE TITLE
Cant index pdf file

### ISSUE THREAD

**Issue by mviejo33** [simon987/sist2#386]
**Device Information (please complete the following information):**
 - OS: `Ubuntu 22.04`
 - Deployment: `Docker`
 - Browser *(if relevant)*: `chrome`
 - SIST2 Version: `v3.1.1`
 - Elasticsearch Version `7.17.9`

**Command with arguments** 
docker-compose file

version: "3"

```
services:
  elasticsearch:
    image: elasticsearch:7.17.9
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "ingest.geoip.downloader.enabled=false"
  sist2-admin:
    image: simon987/sist2:3.1.1-x64-linux
    restart: unless-stopped
    volumes:
      - ./sist2-admin-data/:/sist2-admin/
      - /:/host
    ports:
      - 4090:4090 # sist2
      - 8080:8080 # sist2-admin
    working_dir: /root/sist2-admin/
    entrypoint: python3 /root/sist2-admin/sist2_admin/app.py
```

**Describe the bug**
Tried testing the tool via UI with a single pdf file. Scan passes with no errors, Index fails with no error (or any other line) visible on the UI. However, found **'Error while running task: search backend not found: None'** error in server logs

**Steps To Reproduce**

1. Create a job that reads spanish and english ebooks
2. click on Index

**Expected behavior**
Should see the pdf file in the generated UI

**Actual Behavior**
I dont see the file listed in the corresponding UI

**Screenshots**

[Index fails but no lines were logged](https://drive.google.com/file/d/1qdWZDKQEoJeGSfCR2XUqsyjUkd4wXI5m/view?usp=sharing)
