### ISSUE TITLE
Web options neither work nor persist in sist2-admin

### ISSUE THREAD

**Issue by acotor** [simon987/sist2#400]
**Device Information (please complete the following information):**
 - OS: `[Qnap QTS 5.0.1.2376]`
 - Deployment: `[Docker Standalone 20.10.17-qnap10, Portainer CE 2.18.4]`
 - Browser *(if relevant)*: `[MS Edge, Firefox]`
 - SIST2 Version: `[v3.1.4]`
 - Elasticsearch Version *(if relevant)* : `7.17.9`

**Command with arguments** 
```yml
version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - TZ=Asia/Shanghai
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      network1:
        ipv4_address: 10.0.6.36
  sist2-admin:
    image: simon987/sist2:3.1.4-x64-linux
    restart: unless-stopped
    volumes:
      - /share/SRV/sist2/sist2-admin-data/:/sist2-admin/
      - /share/Archive/DOCLIB:/host
    environment:
      - TZ=Asia/Shanghai
    #ports:
      #- 4090:4090 # sist2
      #- 8080:8080 # sist2-admin
    working_dir: /root/sist2-admin/
    entrypoint: python3 /root/sist2-admin/sist2_admin/app.py
    networks:
      network1:
        ipv4_address: 10.0.6.35
networks:
  network1:
    name: bridge1
    external: true
volumes:
  esdata:
```

**Describe the bug**
Any change to the Web options does not take effects, and was set to default when I enter in the Frontend setting page again.
Including the UI Language, Tagline in navbar, Basic auth, Auth0 options. 

**Steps To Reproduce**
1. Start the stack in portainer.
2. Go to sist2-admin page, then create jobs and start indexing, or use the previous jobs and indexes.
3. Go to a frontend settings page like `default`, or create `newfrontend`,  select indexes, then make changes to basic auth.
4. Start the frontend.
5. Go to the frontend 10.0.6.35:8080, see no basic auth.
6. Go to sist2-admin page, then go back to frontend settings page `default` or `newfront`, see the basic auth is empty.

**Expected behavior**
Any change to the Web options is expected to persist.

**Actual Behavior**
Web options not work.

**Screenshots**
none.

**Additional context**
Indexing and frontend searching are functioning well. And many other containers and stacks work just fine.
