### ISSUE TITLE
Docker cant find the Doc path?

### ISSUE THREAD

**Issue by gerroon** [simon987/sist2#457]
**Device Information (please complete the following information):**
 - OS: eUbuntu 20.04, WSL2
 - Deployment: Docker

Hi

I am using the docker compose as is. So my documents path is `/host/mnt/z/books` I login to `sist2-sist2-admin-1` to check if I can browse that path, and yes I can browse the path in the docker container. So I assumed that should be the actual path that I put in a task job that I created. 

I also tested elastic and the admin panel was able to connect to it.

It returns and error. It seems like it is the wrong path, but how could that be given I test that exact path in the running container?

```
{"sist2-admin": "Starting sist2 command with args ['/root/sist2', 'index', '/sist2-admin/scan-books-2024-01-12 21:23:56.984741.sist2', '--threads=1', '--es-url=http://elasticsearch:9200', '--es-index=sist2', '--batch-size=70', '--incremental-index', '--json-logs', '--very-verbose']"}
{"thread": "T0", "datetime": "2024-01-12 21:24:12", "level": "FATAL", "filepath": "cli.c", "message": "Invalid PATH argument. File not found: /sist2-admin/scan-books-2024-01-12 21:23:56.984741.sist2"}

```
docker compose

```
version: "3"

services:
  elasticsearch:
    image: elasticsearch:7.17.9
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
  sist2-admin:
    image: simon987/sist2:3.3.4-x64-linux
    restart: unless-stopped
    volumes:
      - ./sist2-admin-data/:/sist2-admin/
      - /:/host
    ports:
      - 14090:4090 # sist2
      - 13080:8080 # sist2-admin
    working_dir: /root/sist2-admin/
    entrypoint: python3 /root/sist2-admin/sist2_admin/app.py

```
 

![image](https://github.com/simon987/sist2/assets/8519469/ef323814-6215-4604-a595-bc45ff449a54)
